task(setup): CORE24-112 Basic NX monorepo setup
NorwegianRefugeeCouncil/core pull request #1
Opened 2024-03-11 12:14 UTC by dfigueroa87

Initialised NX by running `npx create-nx-workspace@latest nrc --preset=ts`

2024-03-11 14:26 UTC, neb42 requested changes
You've created an `nrc` folder in the root of the project but the contents of the folder should be at the root.

```
yarn create nx-workspace core
cd core
git init
git remote add ....
etc...
```

2024-03-11 14:26 UTC, neb42 commented on nrc/nx.json
> +  "nxCloudAccessToken": "NDEwZTYzYmUtZDRmNC00MDJjLTg0OTUtNDNhMzM3YmUzZWJjfHJlYWQtd3JpdGU="
I'm unsure whether this should be in git. Have you looked at any best practices for this?

2024-03-11 14:26 UTC, neb42 commented on nrc/package-lock.json
Same `yarn` comment

2024-03-11 14:26 UTC, neb42 commented on nrc/README.md
Probably worth clearing the default readme

2024-03-11 16:00 UTC, dfigueroa87 commented on nrc/.github/workflows/ci.yml
> +      - run: npm ci
I personally just prefer npm because it's the default and doesn't require anything else. But I'm fine with yarn too. I'll re-create everything with `npx create-nx-workspace@latest core --preset=ts --pm=yarn`

2024-03-11 16:05 UTC, dfigueroa87 commented on nrc/nx.json
> +  "nxCloudAccessToken": "NDEwZTYzYmUtZDRmNC00MDJjLTg0OTUtNDNhMzM3YmUzZWJjfHJlYWQtd3JpdGU="
I think it's fine if we configure it as a [read-only token](https://nx.dev/ci/recipes/security/access-tokens#setting-access-tokens). Later on we can define env variables if we want a read-write one. 
After merging this I'll get into NX cloud and figure out how to better configure it.

2024-03-12 09:00 UTC, neb42 approved these changes

2024-03-12 09:38 UTC, merged