Core24 357 frontend display validation response from api
NorwegianRefugeeCouncil/core pull request #103
Opened 2024-06-13 13:46 UTC by neb42

Jira ticket: JIRA-CORE24-357

## What have you implemented?

## How to test it?

## Extra/next steps

2024-06-13 15:39 UTC, dfigueroa87 commented on libs/prm-components/src/lib/components/EntityDetailForm.component.tsx
> +        console.log(issue);
Maybe we should add the `no-console` eslint rule?

2024-06-13 15:39 UTC, dfigueroa87 commented on libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
> +  })();
Why using self invoked functions?

Maybe I'm just not used to them, but I find this way easier to read:
```
const validationError = error && isAxiosError(error) && error.response?.status === 400 ? new ZodError(error.response.data.errors) : null;
```

2024-06-17 08:55 UTC, internetti commented on libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
> +        return `Internal error, contact support. [${error.response?.status}] [${error.response?.data?.message}]`;
if you tell them to contact support, you should at least add an email address, or the link to the helpform

2024-06-17 09:30 UTC, neb42 commented on libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
> +  })();
In this case you're probably right.

Generally I like them when setting a variable with conditional logic, but a separate function feels like overkill.

2024-06-18 08:40 UTC, dfigueroa87 approved these changes

2024-06-18 08:40 UTC, dfigueroa87 commented on libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
> +              to="https://nrc.freshservice.com/a/catalog/request-items/95"
This is the link for core v1, no?

I guess not a big deal at the moment, but we should eventually get it changed

2024-06-18 11:44 UTC, internetti requested changes

2024-06-18 11:44 UTC, internetti commented on libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
> +              to="https://nrc.freshservice.com/a/catalog/request-items/95"
more importantly, this is the one that didn't work, it should be this one:
https://nrc.freshservice.com/support/catalog/items/95

2024-06-19 08:25 UTC, internetti requested changes
when I correct all the errors in the form, the save button doesn't go back to active mode

2024-06-20 10:22 UTC, neb42 commented
> when I correct all the errors in the form, the save button doesn't go back to active mode

Do you have steps to reproduce this? I can't

2024-06-20 13:47 UTC, internetti approved these changes

2024-06-20 13:51 UTC, merged