[CORE24-405] feat(HH): create db table
NorwegianRefugeeCouncil/core pull request #106
Opened 2024-06-17 14:58 UTC by internetti

Jira ticket: JIRA-CORE24-405

## What have you implemented?

created db table for households according to GRF specs and our discussion

## How to test it?

## Extra/next steps

location has to be added later, when we have introduces sites

2024-06-17 15:18 UTC, dfigueroa87 requested changes

2024-06-17 15:18 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +    .dropTableIfExists('household_nationalities');
I think that when you drop the table, all the associated indexes get deleted automatically

2024-06-17 15:18 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +        'female_minor',
In the model I defined them as `adult_male`, and so on, since that was the naming in the spreadsheet.
I'm fine either way, but we need consistency between the model and the table

2024-06-17 15:18 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +    table.string('individual_id').primary().notNullable();
To define composite primary keys, I think you need to define them with `table.primary(['household_id', 'individual_id']);` and not marking several columns as `.primary()`

2024-06-17 15:18 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +      .onDelete('CASCADE');
Not a big deal, as I'm guessing the result is the same. But I think it's easier to read if defining all the columns first, and then adding all the constraints together.

2024-06-17 15:18 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +    table.boolean('is_hoh').notNullable();
I'd prefer if we avoid acronyms as much as possible. Using either `is_head` or `is_head_of_household` here

2024-06-17 15:18 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +    table.unique(['is_hoh', 'individual_id']);
I think this should rather be `household_id` instead of individual. So we ensure there's no more than one head of household for each household

2024-06-17 15:18 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +    table.unique(['household_id', 'individual_id']);
And here I think should be only `individual_id`, since a individual should only be part of one household

2024-06-17 15:18 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +  await knex.schema.createTable('household_nationalities', (table) => {
As I understood it, the household nationality is the nationality of the head of the household. So I think it'd be better to not duplicate that data and directly access it from the individual when joining things. Therefore, I don't think we need this table

2024-06-18 08:20 UTC, neb42 commented on libs/db/migrations/20240617130635_create_household.ts
> +    table.string('individual_id').primary().notNullable();
Small stylistic point. We normally define columns then relationships:

```
table.string('household_id').primary().notNullable();
 table.string('individual_id').primary().notNullable();

table
      .foreign('household_id')
      .references('households.id')
      .onDelete('CASCADE');
...
```

2024-06-18 08:21 UTC, neb42 commented on libs/db/migrations/20240617130635_create_household.ts
> +    table.string('individual_id').primary().notNullable();
Just read a bit further and saw the same comment from David, sorry

2024-06-18 08:34 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +    .dropTableIfExists('household_nationalities');
https://www.postgresql.org/docs/current/sql-droptable.html

:clown_face: 

Not a big deal anyway

2024-06-18 08:36 UTC, dfigueroa87 approved these changes

2024-06-18 08:36 UTC, dfigueroa87 commented on libs/db/migrations/20240617130635_create_household.ts
> +    table.unique(['individual_id']);
:clown_face: 
For this one you could have had it defined in the column definition by adding `.unique()`

2024-06-18 09:05 UTC, merged