[CORE24-116] task(terraform): copy and adjust terraform files from co…
NorwegianRefugeeCouncil/core pull request #12
Opened 2024-03-22 11:27 UTC by internetti

…re v1

Jira ticket: JIRA-CORE24-#

## What have you implemented?
took the terraform files from core v1
these are likely to have to change somehow, but I'll to that in the CD PR

but if anyone already has thoughts here, let them be known

## How to test it?

## Extra/next steps

2024-03-25 09:18 UTC, neb42 requested changes

2024-03-25 09:18 UTC, neb42 commented on deploy/terraform/azurerm_linux_web_app.app.tf
> +resource azapi_update_resource app_auth {
This block can be replaced by updating the version of terraform. See here: https://github.com/NorwegianRefugeeCouncil/icla-duhok/blob/main/deploy/terraform/azurerm_linux_web_app.app.tf

2024-03-25 09:26 UTC, neb42 commented on deploy/terraform/azurerm_postgresql_flexible_server.postgres.tf
> +  version                = "14"
variable

2024-03-25 09:27 UTC, neb42 commented on deploy/terraform/azurerm_postgresql_flexible_server.postgres.tf
> +  zone                   = "1"
variable

2024-03-25 09:27 UTC, neb42 commented on deploy/terraform/azurerm_service_plan.plan.tf
> +  sku_name            = "P1v2"
variable

2024-03-25 10:51 UTC, internetti commented on deploy/terraform/azurerm_postgresql_flexible_server.postgres.tf
> +  storage_mb             = 32768
what about the zone?

2024-03-26 10:50 UTC, neb42 commented on deploy/terraform/azurerm_postgresql_flexible_server.postgres.tf
> +  storage_mb             = var.postgres_storage_mb #32768
Remove the comments

2024-03-26 10:50 UTC, neb42 commented on deploy/terraform/variables.tf
> +}
If we want defaults, they can be added here. I think postgres version can definitely have a default. Tbh they all probably can but we can still configure them if needed.

2024-03-26 10:50 UTC, neb42 commented on deploy/terraform/azurerm_linux_web_app.app.tf
> +  ]
Not to be super pedantic, but some spaces between each of these blocks would really help readability. I wonder if there's some form of terraform linter?

2024-03-26 12:24 UTC, neb42 commented on deploy/terraform/main.tf
> +  }
this can go

2024-03-26 12:25 UTC, neb42 commented on deploy/terraform/main.tf
> +}
and this

2024-04-03 11:13 UTC, neb42 approved these changes

2024-04-03 11:46 UTC, merged