CORE24-160: CD
NorwegianRefugeeCouncil/core pull request #13
Opened 2024-03-25 11:57 UTC by internetti

Jira ticket: JIRA-CORE24-160

## What have you implemented?
added a cd.yml containing the build and deployment steps
added Dockerfiles for app and api

## How to test it?
do `docker build -t core-api -f api.Dockerfile .` locally, see if it works (at 30ee8a5bc7a2ccfc79c9939a41e5003d2cdd0fa3 it doesn't)

## Extra/next steps
fix Dockerfiles
make sure all variables are there and set
set up workflow in github

2024-03-26 12:44 UTC, neb42 requested changes
I think you need to go through and review all of the terraform variables. I've commented what I've noticed but it seems they've come from a copy and paste of a different application and aren't all relevant and may be missing. I think the best way to find them all is to:

1. Go through all of the terraform files and ensure that every `var.xxx` is in the `variables.tf` file. (likely in the other pr first)
2. Go through the variables file and ensure that they are all in the `cd.yml` file (unless a default is being set) and removing any that are not there.

And for the docker image, it's probably quicker to test it locally with a `docker-compose.yml` file rather than testing it through deploying. I would typically do this with a separate compose file that looks like:

```
services:
  core:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - '3000:3000' # or whatever port the api runs on
    environment:
      .....
    depends_on:
      - db
      - oauth2-proxy
      - oidc
```

and then ran with:
`docker compose -f docker-compose.yaml -f docker-compose.api.yaml up -d --build`

2024-03-26 12:44 UTC, neb42 commented on .github/workflows/cd.yml
> +          - prod
this should be `dev` only for now

2024-03-26 12:44 UTC, neb42 commented on .github/workflows/cd.yml
> +      TF_VAR_app_hostname: ${{vars.APP_HOSTNAME}}
remove

2024-03-26 12:44 UTC, neb42 commented on .github/workflows/cd.yml
> +      #TF_VAR_postgres_sku_name: ${{vars.POSTGRES_SKU_NAME}} #
this should be set as it doesn't have a default

2024-03-26 12:44 UTC, neb42 commented on .github/workflows/cd.yml
> +      TF_VAR_postgres_standby_availability_zone: ${{vars.POSTGRES_ZONE}} #
these aren't being used. I think you've just copied the icla-duhok ones which was for mysql but aren't used in pg.

2024-03-26 12:44 UTC, neb42 commented on .github/workflows/cd.yml
> +      #TF_VAR_postgres_iops: ${{vars.POSTGRES_IOPS}} #
remove

2024-03-26 12:44 UTC, neb42 commented on .github/workflows/cd.yml
> +      # TF_VAR_uploads_storage_container_name: ${{vars.UPLOADS_STORAGE_CONTAINER_NAME}} #
remove

2024-03-26 12:44 UTC, neb42 commented on .github/workflows/cd.yml
> +      TF_VAR_container_port: ${{vars.CONTAINER_PORT}}
remove

2024-03-26 12:44 UTC, neb42 commented on .github/workflows/cd.yml
> +      TF_VAR_app_encryption_key: ${{secrets.APP_ENCRYPTION_KEY}} #
remove

2024-03-26 12:44 UTC, neb42 commented on .github/workflows/cd.yml
> +          -backend-config="key=${{vars.ENVIRONMENT}}.tfstate" \
This is going to cause issues as the environment is currently set to `dev` which conflicts with the core-v1 tfstate. Potentially the resource group has the same issue. This is why I suggested using a new azure subscription.

2024-03-26 12:44 UTC, neb42 commented on app.Dockerfile
Delete this

2024-03-26 12:44 UTC, neb42 commented on api.Dockerfile
Delete this

2024-03-26 12:44 UTC, neb42 commented on apps/core-frontend/project.json
> -      "configurations": {}
Any reason for removing this?

2024-03-26 12:44 UTC, neb42 commented on Dockerfile
This isn't setting up the frontend properly. It needs to:

* Build backend
* Build frontend
* Copy frontend build into backend's static files
* Serve backend

Currently the backend is being started then it builds the frontend but does nothing with it.

2024-03-26 14:31 UTC, internetti commented on apps/core-frontend/project.json
> -      "configurations": {}
just because it was empty

2024-03-28 13:54 UTC, dfigueroa87 commented on .github/workflows/cd.yml
> +  workflow_dispatch:
Should also run automatically on pushes to the `main` branch, no?

2024-03-28 13:54 UTC, dfigueroa87 commented on tsconfig.base.json
> +      "tslib": ["./node_modules/tslib/tslib.d.ts"]
I guess this is not needed after solving the dependencies issue we had

2024-04-03 07:44 UTC, neb42 requested changes
`webpack.config.js` still refers to `assets: ['./src/assets'],` which is renamed to `static` causing the build to fail

Check that `docker compose up -d` works and that the app is running.

Also check that the cd workflow runs and deploys the application.

2024-04-03 07:54 UTC, neb42 commented on docker-compose.yaml
> +      PORT: 3333
In `envoy.yaml` there is a port value for web set at `8080`. This probably needs changing to `3333`.

2024-04-03 07:54 UTC, neb42 commented on docker-compose.yaml
> +    depends_on:
Add `envoy` here

2024-04-03 08:55 UTC, internetti commented on .github/workflows/cd.yml
> +          creds: ${{secrets.AZURE_CREDENTIALS}} #
kept them because I still don't have the values for them, not sure where to find them, to they need to be created newly?

2024-04-04 08:20 UTC, neb42 reviewed
I think the frontdoor side is missing. I'd say we address the last comment on this review and merge, as this addresses the scope of this ticket. This missing frontdoor should have been caught in the terraform pr.

2024-04-04 10:41 UTC, neb42 approved these changes

2024-04-04 11:01 UTC, merged