COR-622: (de)activate action in table and search
NorwegianRefugeeCouncil/core pull request #162
Opened 2023-01-10 16:09 UTC by internetti

add new column in individual_registrations, for the activate boolean, true by default
also added as a filter to the search
the actions delete, activate and deactivate have been moved to a meatball menu next to the all-select-checkbox in the table.

2023-01-17 10:25 UTC, neb42 requested changes

2023-01-17 10:25 UTC, neb42 commented on web/templates/searchForm.gohtml
> +            <!-- End Is Active -->
And show only active by default

2023-01-17 10:25 UTC, neb42 commented on web/templates/individuals.gohtml
> +                            </div>
I think this looks cool, but is super hidden. Maybe keep the old delete button, but use the same component as the download button?

2023-01-17 10:25 UTC, neb42 commented on web/templates/individuals.gohtml
> +                            </td>
I like this, but maybe worth checking with Fix if it's clear enough

2023-01-17 10:25 UTC, neb42 commented on internal/db/individual.go
>  }
Actually it's these that aren't used now

2023-01-17 10:25 UTC, neb42 commented on internal/db/const.go
> +	conditions:  []string{"and active IS true"},
The conditions here cause an error:

* In the table select 2 rows, one is inactive and the other is active
* Try to activate or deactivate both
* The filter causes the `rowsAffected` to be `1` not `2`
* There is then a safety check that `rowsAffected = len(ids)`, this fails and errors

I think we just remove the conditions here, but keep the delete condition

2023-01-17 10:46 UTC, internetti commented on internal/api/individual_tabular.go
> +			i.Active = isTrue(cols[idx])
there's a ticket to enable downloading inactive individuals, so the possibility should be there, but yeah, not by default

2023-01-20 08:59 UTC, neb42 requested changes
* Delete button styling is broken
* I think all the buttons need to have text for clarity. Currently we don't say active/inactive/deactivate anywhere other than tooltips
* I'd move the inactive table filter to the search panel
* There's still an error when performing a batch action on a mix of active + inactive. I assume because there's a filter for `inactive = false` being applied somewhere. Actually this also happens when trying to activate a single individual within the list view (again probably because of the filter).

2023-01-20 08:59 UTC, neb42 commented on internal/api/individual_tabular.go
> +			i.Inactive = isFalse(cols[idx])
Why are we looking for false values rather than true?

2023-01-20 08:59 UTC, neb42 commented on internal/db/individual.go
> +
These should be deleted too

2023-01-20 08:59 UTC, neb42 commented on internal/db/migrations/postgres/022_add_inactive_column_to_individual.up.sql
> +    DROP COLUMN IF EXISTS active;
I don't think this is needed. Just teardown your local db

2023-01-20 08:59 UTC, neb42 commented on internal/db/sql_individual_list.go
> +		//	g.writeString(" AND inactive = ").writeArg(true)
Delete

2023-01-20 08:59 UTC, neb42 commented on internal/api/individual_list_options.go
> +	return o.Inactive != nil && !*o.Inactive
Should this be an `or`?

2023-01-20 16:20 UTC, internetti commented on internal/api/individual_tabular.go
> +			i.Inactive = isFalse(cols[idx])
because we have 3 possible values, true, false and nil. true and nil both mean not including inactive users. only false means including them. so it made more sense to explicitly look for false values.

2023-01-27 10:09 UTC, neb42 reviewed
* Delete button on the individual form still has broken css
* Activating/deactivating in the table doesn't preserve the search query

2023-01-27 10:09 UTC, neb42 commented on cmd/template.go
> +			Inactive:                      false,
I'd remove inactive from the template. I think when creating a new file they won't use the inactive field

2023-01-27 10:09 UTC, neb42 commented
conflicts

2023-01-27 11:28 UTC, internetti commented
@neb42 can you give me a screenshot of the broken css of the delete button? I don't see anything wrong

2023-01-27 11:43 UTC, internetti commented
@neb42 about the delete button styling, you might have to run another `make bootstrap`

2023-01-30 08:51 UTC, neb42 commented
The css was down to `make bootstrap`

The query string still isn't being preserved. I think the change is needed in internal/handlers/individuals_action.go, with this block:

```
if options.Inactive != nil && *options.Inactive {
  http.Redirect(w, r, fmt.Sprintf("/countries/%s/individuals?inactive=true", countryID), http.StatusFound)
} else {
  http.Redirect(w, r, fmt.Sprintf("/countries/%s/individuals", countryID), http.StatusFound)
}
```

2023-02-01 10:17 UTC, neb42 approved these changes

2023-02-01 11:07 UTC, merged