COR-626: differentiate read, write and admin permissions
NorwegianRefugeeCouncil/core pull request #166
Opened 2023-01-17 10:16 UTC by internetti

added permission groups for read and write permissions.
the permission levels are hierarchical, i.e. global admin > write > read
the levels are then used to disable/enable features in the frontend

2023-01-17 11:18 UTC, neb42 requested changes

2023-01-17 11:18 UTC, neb42 commented on web/templates/individuals.gohtml
> +        <form id="individuals-action-form" class="table-responsive scroll-body" method="post">
Why remove `opacity-0`?

2023-01-17 11:18 UTC, neb42 commented on web/templates/individuals.gohtml
> +                        />
Probably better to remove this column if they can't write

2023-01-17 11:18 UTC, neb42 commented on internal/auth/interface.go
>  	HasCountryLevelPermission(countryID string, perm Permission) bool
Maybe replace uses of this with the new methods

2023-01-17 11:18 UTC, neb42 commented on web/templates/nav.gohtml
> +                            {{if (.RequestContext.Auth.HasMinimumPermissionWrite .RequestContext.SelectedCountry.ID)}}
Maybe a request context method like `.RequestContext.HasSelectedCountryWritePermission` could clean these uses up a bit

2023-01-17 11:18 UTC, neb42 commented on internal/utils/types.go
> +package utils
Is there a better place these structs could live? I generally don't like putting things in a top level `utils` and also `types.go` is super generic.

2023-01-18 15:29 UTC, internetti commented on internal/utils/types.go
> +package utils
the permissions type is only used in one file, I'll move it there. the other one is used in all kinds of places, I don't know where better to put it

2023-01-18 15:30 UTC, internetti commented on web/templates/individuals.gohtml
> +        <form id="individuals-action-form" class="table-responsive scroll-body" method="post">
this class is removed immediately anyway, it was some kind of hack by ludo to prevent the jumping of the table, but I couldn't observe any jumping anymore, so this hack is obsolete now.

2023-01-18 15:31 UTC, internetti commented on internal/server/middleware/permissions.go
> +		}
the hierarchy was handled in the auth interface, but moving it here does make it a bit cleaner

2023-01-20 09:20 UTC, neb42 reviewed
Before merging this it's probably worth setting up okta groups and azure dev ops variables

2023-01-20 09:20 UTC, neb42 commented on internal/handlers/templates.go
> +	authInterface, err := utils.GetAuthContext(r.Request.Context())
I don't think this is needed. Can you do `r.Auth.HasCountryPermissionWrite` etc

2023-01-20 09:20 UTC, neb42 commented on web/templates/individuals.gohtml
> +            {{ if or .RequestContext.Auth.IsGlobalAdmin .RequestContext.HasSelectedCountryWritePermission}}
Maybe `HasSelectedCountryWritePermission` should return true if you're a global admin? Because that is the case

2023-01-20 09:20 UTC, neb42 commented on web/templates/individuals.gohtml
> +            {{ if or .RequestContext.Auth.IsGlobalAdmin .RequestContext.HasSelectedCountryWritePermission}}
The global admin check doesn't seem to be there for any other places where you need write permissions

2023-01-20 16:11 UTC, internetti commented on internal/handlers/templates.go
> +	authInterface, err := utils.GetAuthContext(r.Request.Context())
I tried that first, threw an error for some reason. now it works. weird.

2023-01-20 16:18 UTC, internetti commented
@neb42 the variables are already set up, at least for the development stage. about the okta groups, how free are we with naming them? I guess for development we can do what we want, but for the others, do we need to consult Mads?

2023-01-25 09:28 UTC, neb42 commented
Tests are failing (I just triggered the build manually)

2023-01-25 13:05 UTC, neb42 approved these changes

2023-01-26 11:08 UTC, merged