COR 678/679: Add is female + minor headed household fields
NorwegianRefugeeCouncil/core pull request #168
Opened 2023-01-18 09:57 UTC by neb42

2023-01-19 09:46 UTC, internetti requested changes
when uploading a freshly generated csv I get the error `failed to parse csv: record on line 2: wrong number of fields`

2023-01-19 09:47 UTC, internetti reviewed
was this meant to be shown in the table?

2023-01-20 13:42 UTC, neb42 commented
> when uploading a freshly generated csv I get the error `failed to parse csv: record on line 2: wrong number of fields`

Not as far as I know

2023-01-20 15:57 UTC, internetti approved these changes

2023-01-23 08:51 UTC, merged