Add service fields
NorwegianRefugeeCouncil/core pull request #176
Opened 2023-01-24 14:24 UTC by neb42

Tests are failing upstream so I'll fix after merging

2023-01-24 15:23 UTC, internetti requested changes

2023-01-24 15:23 UTC, internetti commented on internal/api/service_cc.go
> +		return "", fmt.Errorf("unknown displacement status type: %v", logutils.Escape(str))
```suggestion
		return "", fmt.Errorf("unknown service type: %v", logutils.Escape(str))
```

2023-01-24 15:23 UTC, internetti commented on internal/api/validation/individual.go
> +	allErrs = append(allErrs, validateIndividualServiceCC(i.ServiceCC1, p.Child("serviceCC1"))...)
should we not validate the request and delivery dates? birthday and collection time are validated

2023-01-25 09:57 UTC, internetti commented on internal/api/validation/individual.go
> +		allErrs = append(allErrs, validation.Invalid(path, d, "birthdate cannot be in the future"))
the log message still says birthday.
also, it might be useful to deduplicate all the date validation functions, but that could be done later.

2023-01-25 10:02 UTC, neb42 commented on internal/api/validation/individual.go
> +		allErrs = append(allErrs, validation.Invalid(path, d, "birthdate cannot be in the future"))
Yeah I did think that, but it could be that different dates have different requirements. Eg. some are required, some can be in the future (like a deadline)

2023-01-25 11:14 UTC, internetti approved these changes

2023-01-25 13:18 UTC, merged