WIP
NorwegianRefugeeCouncil/core pull request #19
Opened 2024-04-09 10:33 UTC by internetti

Jira ticket: JIRA-CORE24-#

## What have you implemented?

## How to test it?

## Extra/next steps

2024-04-10 07:24 UTC, neb42 commented on apps/core-frontend/src/clients/api.client.ts
Two comments on this;

1. I think the clients should live in a separate package so that they can be used across services.
2. I think this client works well as a `BaseAPIClient` but we then want specific clients for each feature. So for this I would make a `UserAPIClient` with a `me` method, which would called the `get` endpoint on the base client with `/me`.

2024-04-10 07:25 UTC, neb42 commented on apps/core-frontend/src/components/UserInfo.tsx
> +export const UserInfo: React.FC<UserInfoProps> = ({ ...props }) => {
We should deconstruct props here

2024-04-10 08:56 UTC, internetti commented on apps/core-frontend/src/clients/api.client.ts
yeah, point 2 was also my plan :+1:

2024-04-18 11:36 UTC, neb42 requested changes
Some minor changes. I think the ApiContext isn't quite right but we can review when building out the PRM. I was thinking each feature would have it's own context, but we can see how it plays out and maybe refactor later.

2024-04-18 11:36 UTC, neb42 commented on apps/core-api/src/data-access/user.store.ts
This looks like incorrect linting

2024-04-18 11:36 UTC, neb42 commented on apps/core-api/src/main.ts
> -app.use(limiter);
Don't remove limiter

2024-04-18 11:36 UTC, neb42 commented on apps/core-frontend/src/app/app.tsx
> +  const { Header, Sider, Content } = Layout;
Can this be outside the function?

2024-04-18 11:36 UTC, neb42 commented on apps/core-frontend/src/app/app.tsx
> +        </Header>
This can be a component

2024-04-18 11:36 UTC, neb42 commented on apps/core-frontend/src/app/app.tsx
> +              </Sider>
Component

2024-04-18 11:36 UTC, neb42 commented on apps/core-frontend/src/app/app.tsx
> +                  element={<div className="test">Participants </div>}
Remove class name

2024-04-18 11:36 UTC, neb42 commented on apps/core-frontend/src/components/UserInfo.tsx
> +  return <Typography.Text>{displayName}</Typography.Text>;
Maybe render a few more fields so it looks better for demo

2024-04-18 11:36 UTC, neb42 commented on libs/clients/jest.config.ts
> +  coverageDirectory: '../../coverage/libs/core-clients',
Rename `core-clients` to `clients`

2024-04-18 11:36 UTC, neb42 commented on libs/clients/project.json
> +  "tags": []
Rename `core-clients` to `clients`

2024-04-18 11:36 UTC, neb42 commented on package.json
> +    "react-cookie": "^7.1.4",
I don't think this is needed

2024-04-18 11:36 UTC, neb42 commented on apps/core-frontend/src/main.tsx
> +          >
I'm not sure if this is needed. But I may be wrong here

2024-04-18 12:23 UTC, internetti commented on apps/core-frontend/src/app/app.tsx
> +              </Sider>
I absolutely did not mean to leave the app.tsx like this, definitely moving all of these to components, but as long as the component lib is not clear, the details of this might change so much, that I wanted to do that later

2024-04-18 12:30 UTC, internetti commented on package.json
> +    "react-cookie": "^7.1.4",
not anymore, no. might be needed to store a language cookie later, but I'll remove it for now

2024-04-19 10:43 UTC, neb42 commented on package.json
> +    "@types/cors": "^2.8.17",
Dev dep

2024-04-19 10:56 UTC, neb42 approved these changes

2024-04-19 11:51 UTC, neb42 approved these changes

2024-04-19 11:57 UTC, merged