COR-780: make booleans optional
NorwegianRefugeeCouncil/core pull request #247
Opened 2023-08-30 12:05 UTC by internetti

had to turn all of them into pointers, including inactive and such, so they could be empty in the uploads

2023-09-12 14:13 UTC, internetti commented on web/templates/individuals_columnHeader.gohtml
I wanted to, I just didn't figure out what the correct pattern was, so this was easier. can check again

2023-09-12 14:20 UTC, internetti commented on internal/api/individual.go
> +	Inactive *bool `json:"inactive" db:"inactive"`
It is part of the upload though. And when you have it as a column in the upload, and it is a primitive boolean, the system throws an error if you leave it blank, which goes against the requirement of "nothing is required".
I'd leave it like that, it is treated everywhere as only true, if explicitly true, otherwise false.

2023-09-13 08:40 UTC, neb42 commented on internal/api/individual.go
> +	Inactive *bool `json:"inactive" db:"inactive"`
This really doesn't make sense for this field though. The purpose of the optional field is due to data collection being optional. This isn't a collected field, it's a system field. This needs to be true or false, unknown doesn't have a meaning for inactive. I think we should treat blank as false here.

2023-09-13 08:40 UTC, neb42 commented on web/templates/individuals_columnHeader.gohtml
It probably requires a small change in the template loader

2023-09-13 10:57 UTC, internetti commented on internal/api/individual.go
> +	Inactive *bool `json:"inactive" db:"inactive"`
But this is pretty much what the system does here, treating a blank as false. but to allow blanks, we need to make this a pointer.
and I understand that it is not a collected field, but nonetheless, it's part of the uploads, so we need to handle it. ideally allowing blanks

2023-09-14 09:34 UTC, internetti commented on web/templates/individuals_columnHeader.gohtml
yeah, that's what I tried, and technically the pattern I gave to the loader should have worked, but it doesn't seem to want to recognize subdirectories

2023-09-14 09:49 UTC, internetti commented on web/templates/individuals_columnHeader.gohtml
found the culprit

2023-09-14 10:43 UTC, internetti commented on web/templates/individuals_columnHeader.gohtml
okay, this is not a quick fix, and while I'd love to have subdirectories, I don't think this has a high priority. The ticket is somewhat urgent, so I'd postpone this.

2023-09-21 15:02 UTC, neb42 requested changes

2023-09-21 15:02 UTC, neb42 commented on pkg/views/forms/form.gohtml
> +    <div>{{$field.DisplayName}}</div>
This still needs addressing

2023-09-21 15:02 UTC, neb42 commented on web/templates/individual.gohtml
> +                    {{if boolPointerToValue .Individual.Inactive}}
Why use `boolPointerToValue` here? This is no longer a pointer

2023-09-21 15:02 UTC, neb42 commented on web/templates/individual.gohtml
> +                                    class="btn btn-sm btn-outline-secondary{{if or (not .Individual.Inactive) (eq (boolPointerToValue .Individual.Inactive) false)}} disabled{{end}}"
Same

2023-09-21 15:02 UTC, neb42 commented on web/templates/individuals.gohtml
> +                                    {{end}}
Same

2023-09-21 15:39 UTC, neb42 commented on web/templates/individuals_optionalBoolean.gohtml
Ah, it show blank rather than tick/cross. Not sure it's super clear but it's ok I guess.

2023-09-25 09:35 UTC, neb42 commented on internal/api/enumTypes/optional_boolean.go
> +func TranslateOptionalBoolean(str string) (*bool, error) {
I think this should have a different name. `Translate` sounds like it's a localisation function.

What about:
```
func (g OptionalBoolean) ToBoolPtr() *bool {
  ...
}
```
And then use this in combination with `ParseOptionalBoolean`.

Otherwise this function should maybe renamed to `ParseBoolPtr` for consistency?

2023-09-26 10:30 UTC, merged