fix(upload): CPT-709 use db column ids mapping for identifying columns in files
NorwegianRefugeeCouncil/core pull request #295
Opened 2024-01-23 16:54 UTC by dfigueroa87

The issue was that we were comparing the localised header of the columns in the file to the name of the columns in the database, which in this case were `ID` against `id`, resulting in that column not being considered in the deduplication process.

Additionally found another similar issue, that was causing the `FindDuplicatesInUUIDColumn` function to never be executed, since it was trying to find a file column header named `file_id`. So I fixed it using the same approach above.

2024-01-26 10:56 UTC, neb42 requested changes
This works when just updating rows. But if I upload a file with 1 row for an update and 1 row for a create, it will throw the same false positive duplicate.

2024-01-26 20:43 UTC, dfigueroa87 commented
> This works when just updating rows. But if I upload a file with 1 row for an update and 1 row for a create, it will throw the same false positive duplicate.

@neb42 I tested updating and adding in the same file and that doesn't seem to be a problem. 
What I found to be a problem though is the strategy for comparing emails, and potentially any other field that allows empty strings. This is because the cross join will consider blank emails as the same email. 
Is there a reason for using empty strings instead of nulls? I think that's that would be the best solution for this problem. The alternative is to change all deduplication queries to consider empty strings, which would make all queries more complicated (less readable / maintainable).

2024-01-29 09:36 UTC, neb42 commented
> > This works when just updating rows. But if I upload a file with 1 row for an update and 1 row for a create, it will throw the same false positive duplicate.
> 
> @neb42 I tested updating and adding in the same file and that doesn't seem to be a problem. What I found to be a problem though is the strategy for comparing emails, and potentially any other field that allows empty strings. This is because the cross join will consider blank emails as the same email. Is there a reason for using empty strings instead of nulls in the database? I think that's that would be the best solution for this problem. The alternative is to change all deduplication queries to consider empty strings, which would make all queries more complicated (less readable / maintainable).
> 
> Another limitation I found in the deduplication strategy for emails is that at the moments it's just comparing with the same email field but not the others, i.e. `email_1` only against `email_1`, `email_2` against `email_2` and so on. So if adding a new participant with a second email that an existing participant has as first email, the deduplication check will allow it. Is that behaviour expected?

I think both changes make sense. But maybe check with Fix/Masa first.

2024-01-29 13:10 UTC, dfigueroa87 commented
@neb42 I created https://norwegianrefugeecouncil.atlassian.net/browse/CPT-717 and https://norwegianrefugeecouncil.atlassian.net/browse/CPT-718 for those 2 issues, to keep changes smaller and more specific. So this PR just fixes the issue specified in https://norwegianrefugeecouncil.atlassian.net/browse/CPT-709

2024-02-01 13:50 UTC, dfigueroa87 commented
@neb42 is it fine if I merge this one? I'm taking care of the other issues in the different tickets/PRs.

2024-02-01 16:30 UTC, neb42 approved these changes

2024-02-01 16:50 UTC, merged