[CORE24-122] task(setup): use docker compose for db and oidc local dev dependencies
NorwegianRefugeeCouncil/core pull request #5
Opened 2024-03-19 12:12 UTC by dfigueroa87

Jira ticket: JIRA-CORE24-122

## What have you implemented?

Created a docker compose file for starting db and oidc servers for local development.
Added scripts for the `core-api` project to run docker compose commands + a `local-serve` command concatenating `up` and `serve`.

Note this PR is based on the backend skeleton branch, which wasn't merged yet.
Also, these dependencies are not being used yet, so I configured them in a very basic way to delay decisions until they can be more specific.

## How to test it?

`npx nx run core-api:local-serve` should start the db and oidc containers and then serve the application.
`npx nx run core:api:compose:up` and `npx nx run core:api:compose:down` should do compose ups and downs respectively.

## Extra/next steps

No

2024-03-20 08:38 UTC, neb42 requested changes

2024-03-20 08:38 UTC, neb42 commented on docker-compose.yaml
> +      - "9000:9000"
These are better managed in a file and I think there some config missing.

```
  oidc:
    image: qlik/simple-oidc-provider
    volumes:
      - ./oidc-config.json:/etc/config.json
      - ./oidc-users.json:/etc/users.json
    environment:
      REDIRECTS: https://oauth2.core.dev:10000/oauth2/callback
      CONFIG_FILE: /etc/config.json
      USERS_FILE: /etc/users.json
    healthcheck:
      test: curl http://localhost/.well-known/openid-configuration
    ports:
      - "9000:9000"
   ```

2024-03-20 08:38 UTC, neb42 commented on docker-compose.yaml
We need an envoy proxy here too. The same as v1 should be fine.

2024-03-20 13:44 UTC, dfigueroa87 commented on docker-compose.yaml
Added envoy and oauth2-proxy, pretty much all copied from v1

2024-03-21 09:33 UTC, neb42 approved these changes
I think the envoy file may need to change because we're moving from a server to a client/server model that run on different ports locally. Once things are all merged this can be resolved in a different pr.

2024-03-21 09:58 UTC, merged