Core24 223 render create participant form visuals
NorwegianRefugeeCouncil/core pull request #60
Opened 2024-05-03 09:16 UTC by neb42

Jira ticket: JIRA-CORE24-#

## What have you implemented?

* Style entity form
* Add some blocks in when leaving a dirty form

## How to test it?

## Extra/next steps

* Styling is based on core v1. Better ui/ux needed in the future but I think this is good enough for now

2024-05-03 10:44 UTC, internetti reviewed
getting this error in storybook: 
`useNavigate() may be used only in the context of a <Router> component.`

2024-05-06 10:00 UTC, internetti requested changes
could we include the error feedback in the fixed header? or put them in their own fixed header? otherwise hard to see that there actually is one

can we theme the checkboxes orange? or is that a different ticket?

and I think the disability levels should not only be the numbers, we should add the labels from the grf excel. if you don't want to do that in this pr, a ticket would be good, to not forget it

2024-05-06 10:57 UTC, neb42 commented
> could we include the error feedback in the fixed header? or put them in their own fixed header? otherwise hard to see that there actually is one

Not sure if I agree, but either way I would leave this for the validation pr.

> can we theme the checkboxes orange? or is that a different ticket?

I've left theming out of this

> and I think the disability levels should not only be the numbers, we should add the labels from the grf excel. if you don't want to do that in this pr, a ticket would be good, to not forget it

I was going to leave this (and others) for the translation pr.

2024-05-06 17:19 UTC, internetti approved these changes

2024-05-07 06:35 UTC, merged