Core24 237 239 41 finalise entity detail frontend
NorwegianRefugeeCouncil/core pull request #62
Opened 2024-05-06 14:38 UTC by neb42

Jira ticket: JIRA-CORE24-237
Jira ticket: JIRA-CORE24-239
Jira ticket: JIRA-CORE24-41

## What have you implemented?

* Validate payloads and responses in api controller so that default values are sent (eg. sending no email addresses gets parsed to an empty array)
* Configure more optional fields
* Change client to use put for updates
* Use disabled form for read only view
* Ensure correct navigation, data flow, alert showing, etc when switching between create/edit/read modes

## How to test it?

## Extra/next steps

* The read only mode looks bad. It's functional but not production ready.

2024-05-06 17:18 UTC, internetti requested changes
when clicking save, the 'do you want to leave' alert pops up, that's confusing.

2024-05-07 07:43 UTC, internetti requested changes
now I get this error in the console after saving: 
`"Error: No route matches URL "/prm/participants/01HX8ZKRYC2WD73H4H33ZMMVRN""`

also, this might not be from this PR, I don't immediately see something causing this, but when starting to enter something into an input field, there's an error in the console about an uncontrolled input being turned into a controlled input. I had fixed that at some point by setting an empty default value

2024-05-07 08:53 UTC, internetti requested changes
and there's a warning about the allowToggle on the accordion, apparently that's not used when allowMultiple is used

2024-05-07 09:32 UTC, neb42 commented
> and there's a warning about the allowToggle on the accordion, apparently that's not used when allowMultiple is used

This is resolved

2024-05-07 12:50 UTC, internetti commented on libs/prm-components/src/lib/hooks/useApiReducer.hook.ts
> +          return defaultState;
if this is used for the idle case, and not the default case, I'd call it idleState?

2024-05-07 13:22 UTC, internetti approved these changes

2024-05-07 13:30 UTC, dfigueroa87 approved these changes

2024-05-07 13:32 UTC, merged