Task/core24 114 frontend skeleton
NorwegianRefugeeCouncil/core pull request #7
Opened 2024-03-20 10:29 UTC by internetti

Jira ticket: JIRA-CORE24-114

## What have you implemented?
created a frontend skeleton using the nx generator with vite, cypress, sass and react

## How to test it?
nx run core-frontend:build
nx run core-frontend:preview

## Extra/next steps
tests are still having an issue

2024-03-21 09:53 UTC, neb42 requested changes
With the changes to `vite.config.ts` and the `module` field in `package.json`, you should be able to rename the `.cjs` files back to `.js`.

2024-03-21 09:53 UTC, neb42 commented on apps/core-frontend/src/app/app.tsx
> +export default App;
On the backend setup we decided to use named exports only. So remove this line and add an export to line 3

2024-03-21 09:53 UTC, neb42 commented on apps/core-frontend/vite.config.ts
> +  },
I don't think this is needed if we stop using react native

2024-03-21 09:53 UTC, neb42 commented on package.json
>    }
Remove this

2024-03-21 09:53 UTC, neb42 commented on package.json
> +  "type": "module",
Remove this

2024-03-21 09:53 UTC, neb42 commented on package.json
> +    "react-native-web": "0.17.1",
Remove

2024-03-21 09:53 UTC, neb42 commented on package.json
> +    "@expo-google-fonts/roboto": "~0.2.2",
Remove

2024-03-21 09:56 UTC, dfigueroa87 commented on apps/core-frontend/project.json
> +          "buildTarget": "core-api:build:production"
Shouldn't these two be `core-frontend`?

2024-03-21 11:37 UTC, internetti commented on apps/core-frontend/project.json
> +          "buildTarget": "core-api:build:production"
of course. even after fixing this, it still seems to run the production as default, any ideas as to why?

2024-03-21 11:54 UTC, dfigueroa87 commented on apps/core-frontend/project.json
> +          "buildTarget": "core-api:build:production"
I'm guessing the `production` logged when running the build comes from vite and it's not related to this. Removing the production config and running the development build explicitly still works and logs the same

2024-03-21 13:31 UTC, dfigueroa87 reviewed
Looks good to me, you just seem to have some formatting issues in these files:
apps/core-frontend-e2e/tsconfig.json
apps/core-frontend/project.json

2024-03-21 15:41 UTC, dfigueroa87 approved these changes

2024-03-22 10:57 UTC, neb42 approved these changes

2024-03-22 11:24 UTC, merged